//============================================================================
// kronos_memremap.cpp -- PROTOTYPE mem.dll hook-relocation shim for tribes53f.
//
// WHY: mem.dll is a PACKED dll. At runtime it unpacks and installs 62 detour
// hooks at HARDCODED stock-1.30 addresses (jmp/call into its unpacked code,
// NOP-outs, flag tweaks). The 5.3 rebuild tribes53f.exe has a DIFFERENT code
// layout, so mem's hooks land on the WRONG code -> corruption -> crash.
//
// This shim runs as a mem PLUGIN (getPlugin descriptor; its init vtable[0] is
// called by mem AFTER it has applied its patches and the console is ready). It:
//   1. GUARD: confirm we are inside tribes53f (our-original bytes present at the
//      relocated addresses). If not (e.g. loaded into stock Tribes.exe), do
//      NOTHING -- never corrupt a non-tribes53f host.
//   2. For every one of the 62 sites: read mem's live patch at stock VA S, then
//      RESTORE tribes53f's own original bytes at S (undo mem's corruption of our
//      unrelated code there). This alone should let tribes53f+mem boot instead
//      of crashing.
//   3. RELOCATE the actionable hooks to our real function addresses (ourS):
//        kind 1 (verbatim): NOP/const patch is position-independent -> write
//                           mem's captured bytes at ourS.
//        kind 2 (jmp-reloc): mem installed `jmp T` to a REPLACEMENT(ret) handler
//                           -> recompute rel32 to the SAME runtime T at ourS.
//        kind 0 (deferred): complex trampoline (indirect / jmp-into-memcode /
//                           mid-fn) -- restored only, not yet relocated.
//
// Table (SITES[], NUM_SITES) is auto-generated by scratchpad/gentable.py from a
// READ-ONLY runtime memory diff (memdiff.py) of a live mem-loaded process vs the
// on-disk exe, cross-referenced against the Ghidra stock function table.
//
// PROTOTYPE SCOPE: prove (a) tribes53f+mem boots without the corruption crash and
// (b) >=1 relocated hook demonstrably fires at our address. The 6 deferred + the
// ~25 ABSENT-function hooks are follow-up work (byte-match those functions).
//============================================================================
#include <windows.h>
#include <cstdio>
#include <cstring>
#include "remap_table.h"   // HookSite SITES[]; NUM_SITES

static void flog(const char* fmt, ...)
{
    FILE* f = fopen("kronos_memremap.log", "a"); if (!f) return;
    va_list ap; va_start(ap, fmt); vfprintf(f, fmt, ap); va_end(ap);
    fputc('\n', f); fclose(f);
}

// write `len` bytes at absolute VA `addr`, temporarily making the page writable.
static void writeCode(unsigned addr, const unsigned char* bytes, int len)
{
    DWORD oldp;
    if (!VirtualProtect((void*)addr, len, PAGE_EXECUTE_READWRITE, &oldp)) return;
    memcpy((void*)addr, bytes, len);
    VirtualProtect((void*)addr, len, oldp, &oldp);
    FlushInstructionCache(GetCurrentProcess(), (void*)addr, len);
}

// GUARD: is this really tribes53f? Check a handful of relocated sites: our exe's
// bytes at ourS must equal the captured ourorig. Mem never touches ourS, so this
// is stable regardless of mem's patching. Refuse to act otherwise.
static bool hostIsOurBuild()
{
    int checks = 0, ok = 0;
    for (int i = 0; i < NUM_SITES && checks < 6; i++) {
        if (!SITES[i].relocatable) continue;
        checks++;
        if (memcmp((void*)SITES[i].ourS, SITES[i].ourorig, SITES[i].L) == 0) ok++;
    }
    return checks > 0 && ok == checks;
}

static void applyRemap()
{
    if (!hostIsOurBuild()) {
        flog("GUARD FAIL: host is not tribes53f (relocated-site signatures absent). Doing nothing.");
        return;
    }
    int restored = 0, verbatim = 0, jmpreloc = 0, deferred = 0;
    for (int i = 0; i < NUM_SITES; i++) {
        const HookSite* s = &SITES[i];
        unsigned char cur[32];
        memcpy(cur, (void*)s->S, s->L);            // mem's live patch at stock S

        // 1. restore our own original bytes at S (undo mem's corruption)
        writeCode(s->S, s->mineAtS, s->L);
        restored++;

        if (!s->relocatable) continue;

        // 2. re-apply the hook at our real address
        if (s->kind == 1) {                        // NOP/const: position-independent
            writeCode(s->ourS, cur, s->L);
            verbatim++;
        } else if (s->kind == 2 && cur[0] == 0xE9 && s->L >= 5) {
            int rel; memcpy(&rel, cur + 1, 4);
            unsigned T = s->S + 5 + (unsigned)rel; // mem's runtime handler
            unsigned char jb[5]; jb[0] = 0xE9;
            int nrel = (int)(T - (s->ourS + 5));
            memcpy(jb + 1, &nrel, 4);
            writeCode(s->ourS, jb, 5);
            jmpreloc++;
        } else {
            deferred++;                            // kind 0 complex: restored only
        }
    }
    flog("memremap: restored=%d relocated(verbatim=%d jmp=%d) deferred=%d of %d sites",
         restored, verbatim, jmpreloc, deferred, NUM_SITES);
}

// ---- Kronos plugin descriptor (mem calls vtable[0] after console is ready) ----
__declspec(naked) void myInit()
{
    __asm {
        pushad
        call applyRemap
        popad
        mov  eax, 1
        ret
    }
}

static unsigned g_vtable[8];
static unsigned g_desc[10];

extern "C" __declspec(dllexport) void* getPlugin()
{
    g_vtable[0] = (unsigned)&myInit;
    // vtable[1..7]: same engine-callback slots the datetime plugin publishes.
    // (unused by this plugin, but the loader reads the descriptor uniformly.)
    g_vtable[1] = 0x005f40d8; g_vtable[2] = 0x005f450c; g_vtable[3] = 0x005f3ff8;
    g_vtable[4] = 0x005f3f10; g_vtable[5] = 0x005f4138; g_vtable[6] = 0x005f41a8;
    g_vtable[7] = 0x005f3ddc;
    g_desc[0] = (unsigned)g_vtable;
    g_desc[1] = 0xbaadf00d;
    g_desc[2] = 0x00000000; g_desc[3] = 0x40100000;         // version double => 4.0
    g_desc[4] = (unsigned)"MemRemap";
    g_desc[5] = (unsigned)"tribes53f mem.dll hook relocation (prototype)";
    g_desc[6] = 0;
    g_desc[7] = 3;                                           // client|server
    g_desc[8] = 0xbaadf00d; g_desc[9] = 0xbaadf00d;
    return g_desc;
}

BOOL WINAPI DllMain(HINSTANCE hinst, DWORD reason, LPVOID)
{
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(hinst);
        HMODULE self = NULL;
        GetModuleHandleExW(GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS | GET_MODULE_HANDLE_EX_FLAG_PIN,
                           (LPCWSTR)(void*)&myInit, &self);
        flog("--- kronos_memremap loaded ---");
    }
    return TRUE;
}
