NewActionMap("actionMap.sae");
bindAction(keyboard0, make, "tab", TO, IDACTION_MENU_PAGE, 1.000000);
bindAction(keyboard0, make, "escape", TO, IDACTION_ESCAPE_PRESSED, 0.000000);
bindAction(keyboard0, make, "k", TO, IDACTION_MENU_PAGE, 2.000000);
bindAction(keyboard0, make, "u", TO, IDACTION_CHAT_DISP_SIZE, -1.000000);
bindAction(keyboard0, make, "prior", TO, IDACTION_CHAT_DISP_PAGE, -1.000000);
bindAction(keyboard0, make, "next", TO, IDACTION_CHAT_DISP_PAGE, 1.000000);
bindCommand(keyboard0, make, control, "x", TO, "commandAck();");
bindCommand(keyboard0, make, control, "c", TO, "commandCompleted();");
bindCommand(keyboard0, make, control, "y", TO, "voteYes();");
bindCommand(keyboard0, make, control, "n", TO, "voteNo();");
bindCommand(keyboard0, make, control, "e", TO, "targetClient();");
bindAction(keyboard0, make, "y", TO, IDACTION_CHAT, 1.000000);
bindCommand(keyboard0, make, shift, "1", TO, "CmdInventoryGui::buyFavorites(1);");
bindCommand(keyboard0, make, shift, "2", TO, "CmdInventoryGui::buyFavorites(2);");
bindCommand(keyboard0, make, shift, "3", TO, "CmdInventoryGui::buyFavorites(3);");
bindCommand(keyboard0, make, shift, "4", TO, "CmdInventoryGui::buyFavorites(4);");
bindCommand(keyboard0, make, shift, "5", TO, "CmdInventoryGui::buyFavorites(5);");
bindCommand(keyboard0, make, control, "o", TO, "commandDeclined();");
bindCommand(keyboard0, make, "n", TO, "sendControl(\"n\");");
bindAction(keyboard0, make, "p", TO, IDACTION_CHAT, 0.000000);
bindCommand(keyboard0, make, "c", TO, "remoteEval(2048, ToggleCommandMode);");
bindCommand(keyboard0, make, "]", TO, "CmdHud::turnOn(Large, 1);");
bindCommand(keyboard0, make, "[", TO, "CmdHud::turnOn(Small, 2);");
bindCommand(keyboard0, make, "i", TO, "InvHud::turnOn(0);");
bindCommand(keyboard0, make, "o", TO, "CmdHud::ObjectiveOn();");
bindCommand(keyboard0, make, "0", TO, "sendControl(\"0\");");
bindCommand(keyboard0, make, "numpad1", TO, "sendControl(\"numpad1\");");
bindCommand(keyboard0, make, "numpad2", TO, "sendControl(\"numpad2\");");
bindCommand(keyboard0, make, "numpad3", TO, "sendControl(\"numpad3\");");
bindCommand(keyboard0, make, "numpad4", TO, "sendControl(\"numpad4\");");
bindCommand(keyboard0, make, "numpad5", TO, "sendControl(\"numpad5\");");
bindCommand(keyboard0, make, "numpad6", TO, "sendControl(\"numpad6\");");
bindCommand(keyboard0, make, "numpad7", TO, "sendControl(\"numpad7\");");
bindCommand(keyboard0, make, "numpad8", TO, "sendControl(\"numpad8\");");
bindCommand(keyboard0, make, "numpad9", TO, "sendControl(\"numpad9\");");
bindCommand(keyboard0, make, "numpad0", TO, "sendControl(\"numpad0\");");
bindCommand(keyboard0, make, "numpad+", TO, "sendControl(\"numpad+\");");
bindCommand(keyboard0, make, "numpad-", TO, "sendControl(\"numpad-\");");
bindCommand(keyboard0, make, "numpad*", TO, "sendControl(\"numpad*\");");
bindCommand(keyboard0, make, "numpad/", TO, "sendControl(\"numpad/\");");
bindCommand(keyboard0, make, "numpadenter", TO, "sendControl(\"numpadenter\");");
bindCommand(keyboard0, make, control, "numpad1", TO, "sendControl(\"numpad1\", \"control\");");
bindCommand(keyboard0, make, control, "numpad2", TO, "sendControl(\"numpad2\", \"control\");");
bindCommand(keyboard0, make, control, "numpad3", TO, "sendControl(\"numpad3\", \"control\");");
bindCommand(keyboard0, make, control, "numpad4", TO, "sendControl(\"numpad4\", \"control\");");
bindCommand(keyboard0, make, control, "numpad5", TO, "sendControl(\"numpad5\", \"control\");");
bindCommand(keyboard0, make, control, "numpad6", TO, "sendControl(\"numpad6\", \"control\");");
bindCommand(keyboard0, make, control, "numpad7", TO, "sendControl(\"numpad7\", \"control\");");
bindCommand(keyboard0, make, control, "numpad8", TO, "sendControl(\"numpad8\", \"control\");");
bindCommand(keyboard0, make, control, "numpad9", TO, "sendControl(\"numpad9\", \"control\");");
bindCommand(keyboard0, make, control, "numpad0", TO, "sendControl(\"numpad0\", \"control\");");
bindCommand(keyboard0, make, control, "numpad+", TO, "sendControl(\"numpad+\", \"control\");");
bindCommand(keyboard0, make, control, "numpad-", TO, "sendControl(\"numpad-\", \"control\");");
bindCommand(keyboard0, make, control, "numpad*", TO, "sendControl(\"numpad*\", \"control\");");
bindCommand(keyboard0, make, control, "numpad/", TO, "sendControl(\"numpad/\", \"control\");");
bindCommand(keyboard0, make, control, "numpadenter", TO, "sendControl(\"numpadenter\", \"control\");");
bindCommand(keyboard0, make, shift, "numpad1", TO, "sendControl(\"numpad1\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad2", TO, "sendControl(\"numpad2\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad3", TO, "sendControl(\"numpad3\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad4", TO, "sendControl(\"numpad4\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad5", TO, "sendControl(\"numpad5\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad6", TO, "sendControl(\"numpad6\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad7", TO, "sendControl(\"numpad7\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad8", TO, "sendControl(\"numpad8\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad9", TO, "sendControl(\"numpad9\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad0", TO, "sendControl(\"numpad0\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad+", TO, "sendControl(\"numpad+\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad-", TO, "sendControl(\"numpad-\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad*", TO, "sendControl(\"numpad*\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpad/", TO, "sendControl(\"numpad/\", \"shift\");");
bindCommand(keyboard0, make, shift, "numpadenter", TO, "sendControl(\"numpadenter\", \"shift\");");
bindCommand(keyboard0, make, alt, "numpad1", TO, "sendControl(\"numpad1\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad2", TO, "sendControl(\"numpad2\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad3", TO, "sendControl(\"numpad3\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad4", TO, "sendControl(\"numpad4\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad5", TO, "sendControl(\"numpad5\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad6", TO, "sendControl(\"numpad6\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad7", TO, "sendControl(\"numpad7\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad8", TO, "sendControl(\"numpad8\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad9", TO, "sendControl(\"numpad9\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad0", TO, "sendControl(\"numpad0\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad+", TO, "sendControl(\"numpad+\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad-", TO, "sendControl(\"numpad-\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad*", TO, "sendControl(\"numpad*\", \"alt\");");
bindCommand(keyboard0, make, alt, "numpad/", TO, "sendControl(\"numpad/\", \"alt\");");
bindCommand(keyboard0, make, "f1", TO, "sendControl(\"f1\");");
bindCommand(keyboard0, make, "f2", TO, "sendControl(\"f2\");");
bindCommand(keyboard0, make, "f3", TO, "sendControl(\"f3\");");
bindCommand(keyboard0, make, "f4", TO, "sendControl(\"f4\");");
bindCommand(keyboard0, make, "f5", TO, "sendControl(\"f5\");");
bindCommand(keyboard0, make, "f6", TO, "sendControl(\"f6\");");
bindCommand(keyboard0, make, "f7", TO, "sendControl(\"f7\");");
bindCommand(keyboard0, make, "f8", TO, "sendControl(\"f8\");");
bindCommand(keyboard0, make, "f9", TO, "sendControl(\"f9\");");
bindCommand(keyboard0, make, "f10", TO, "sendControl(\"f10\");");
bindCommand(keyboard0, make, "f11", TO, "sendControl(\"f11\");");
bindCommand(keyboard0, make, "f12", TO, "sendControl(\"f12\");");
bindCommand(keyboard0, make, control, "1", TO, "sendControl(\"1\", \"control\");");
bindCommand(keyboard0, make, control, "2", TO, "sendControl(\"2\", \"control\");");
bindCommand(keyboard0, make, control, "3", TO, "sendControl(\"3\", \"control\");");
bindCommand(keyboard0, make, control, "4", TO, "sendControl(\"4\", \"control\");");
bindCommand(keyboard0, make, control, "5", TO, "sendControl(\"5\", \"control\");");
bindCommand(keyboard0, make, control, "6", TO, "sendControl(\"6\", \"control\");");
bindCommand(keyboard0, make, control, "7", TO, "sendControl(\"7\", \"control\");");
bindCommand(keyboard0, make, control, "8", TO, "sendControl(\"8\", \"control\");");
bindCommand(keyboard0, make, control, "9", TO, "sendControl(\"9\", \"control\");");
bindCommand(keyboard0, make, control, "0", TO, "sendControl(\"0\", \"control\");");
bindCommand(keyboard0, make, alt, "1", TO, "sendControl(\"1\", \"alt\");");
bindCommand(keyboard0, make, alt, "2", TO, "sendControl(\"2\", \"alt\");");
bindCommand(keyboard0, make, alt, "3", TO, "sendControl(\"3\", \"alt\");");
bindCommand(keyboard0, make, alt, "4", TO, "sendControl(\"4\", \"alt\");");
bindCommand(keyboard0, make, alt, "5", TO, "sendControl(\"5\", \"alt\");");
bindCommand(keyboard0, make, alt, "6", TO, "sendControl(\"6\", \"alt\");");
bindCommand(keyboard0, make, alt, "7", TO, "sendControl(\"7\", \"alt\");");
bindCommand(keyboard0, make, alt, "8", TO, "sendControl(\"8\", \"alt\");");
bindCommand(keyboard0, make, alt, "9", TO, "sendControl(\"9\", \"alt\");");
bindCommand(keyboard0, make, alt, "0", TO, "sendControl(\"0\", \"alt\");");
NewActionMap("playMap.sae");
bindCommand(keyboard0, make, "m", TO, "throwStart();");
bindCommand(keyboard0, break, "m", TO, "throwRelease(\"Mine\");");
bindCommand(keyboard0, make, "1", TO, "use(\"Blaster\");");
bindCommand(keyboard0, make, "3", TO, "use(\"Chaingun\");");
bindCommand(keyboard0, make, "4", TO, "use(\"Disc Launcher\");");
bindCommand(keyboard0, make, "6", TO, "use(\"Laser Rifle\");");
bindCommand(keyboard0, make, "7", TO, "use(\"ELF gun\");");
bindCommand(keyboard0, make, "8", TO, "use(\"Mortar\");");
bindCommand(keyboard0, make, "9", TO, "use(\"Targeting Laser\");");
bindCommand(keyboard0, make, "h", TO, "use(\"Repair Kit\");");
bindCommand(keyboard0, make, control, "a", TO, "drop(Ammo);");
bindCommand(keyboard0, make, control, "f", TO, "drop(Flag);");
bindCommand(keyboard0, make, control, "k", TO, "kill();");
bindAction(keyboard0, make, "r", TO, IDACTION_SNIPER_FOV, 1.000000);
bindAction(keyboard0, break, "r", TO, IDACTION_SNIPER_FOV, 0.000000);
bindAction(keyboard0, make, "x", TO, IDACTION_VIEW);
bindAction(keyboard0, make, "z", TO, IDACTION_INC_SNIPER_FOV, 1.000000);
bindCommand(keyboard0, make, control, "p", TO, "drop(Backpack);");
bindCommand(keyboard0, make, "g", TO, "throwStart();");
bindCommand(keyboard0, break, "g", TO, "throwRelease(\"Grenade\");");
bindCommand(keyboard0, make, "5", TO, "use(\"Grenade Launcher\");");
bindAction(keyboard0, make, "left", TO, IDACTION_TURNLEFT, 0.099855);
bindAction(keyboard0, break, "left", TO, IDACTION_TURNLEFT, 0.000000);
bindAction(keyboard0, make, "right", TO, IDACTION_TURNRIGHT, 0.099855);
bindAction(keyboard0, break, "right", TO, IDACTION_TURNRIGHT, 0.000000);
bindAction(joystick0, rzaxis0, TO, IDACTION_RUN, Center, DeadZone, 0.099571, Scale, 1.000000);
bindCommand(keyboard0, make, "t", TO, "use(\"Backpack\");");
bindAction(joystick0, xaxis0, TO, IDACTION_YAW, Center, DeadZone, 0.099571, Scale, 0.099571);
bindAction(joystick0, yaxis0, TO, IDACTION_PITCH, Center, DeadZone, 0.099571, Scale, 0.099571);
bindAction(joystick0, zaxis0, TO, IDACTION_RUN, Center, DeadZone, 0.500000, Scale, 1.000000);
bindAction(mouse0, make, button1, TO, IDACTION_JET, 1.000000);
bindAction(mouse0, break, button1, TO, IDACTION_JET, 0.000000);
bindAction(keyboard0, make, "space", TO, IDACTION_MOVEUP);
bindAction(mouse0, make, button0, TO, IDACTION_FIRE1);
bindAction(mouse0, break, button0, TO, IDACTION_BREAK1);
bindCommand(keyboard0, make, control, "w", TO, "prevWeapon();");
bindCommand(keyboard0, make, control, "q", TO, "drop(Weapon);");
bindCommand(keyboard0, make, "b", TO, "use(\"beacon\");");
bindAction(mouse0, xaxis0, TO, IDACTION_YAW, Flip, Scale, 0.003778);
bindAction(mouse0, yaxis0, TO, IDACTION_PITCH, Flip, Scale, 0.003778);
bindCommand(keyboard0, make, control, "v", TO, "Menu::DisplayDefault();");
bindCommand(keyboard0, break, control, "v", TO, "");
bindCommand(keyboard0, make, "v", TO, "Menu::Display(menuChat);");
bindCommand(keyboard0, break, "v", TO, "");
bindCommand(keyboard0, make, control, "d", TO, "Menu::Display(menuDrop);");
bindCommand(keyboard0, break, control, "d", TO, "");
bindCommand(keyboard0, make, control, "g", TO, "Job::Start();");
bindCommand(keyboard0, break, control, "g", TO, "");
bindCommand(keyboard0, make, control, "h", TO, "HUD::ToggleDisplay(hudDyn);");
bindCommand(keyboard0, break, control, "h", TO, "");
bindCommand(keyboard0, make, control, "t", TO, "TeamHUD::ToggleDisplay();");
bindCommand(keyboard0, break, control, "t", TO, "");
bindCommand(keyboard0, make, control, "m", TO, "Menu::Display(menuMute);");
bindCommand(keyboard0, break, control, "m", TO, "");
bindAction(keyboard0, make, "w", TO, IDACTION_MOVEFORWARD, 1.000000);
bindAction(keyboard0, break, "w", TO, IDACTION_MOVEFORWARD, 0.000000);
bindAction(keyboard0, make, "a", TO, IDACTION_MOVELEFT, 1.000000);
bindAction(keyboard0, break, "a", TO, IDACTION_MOVELEFT, 0.000000);
bindAction(keyboard0, make, "s", TO, IDACTION_MOVEBACK, 1.000000);
bindAction(keyboard0, break, "s", TO, IDACTION_MOVEBACK, 0.000000);
bindAction(keyboard0, make, "d", TO, IDACTION_MOVERIGHT, 1.000000);
bindAction(keyboard0, break, "d", TO, IDACTION_MOVERIGHT, 0.000000);
bindCommand(keyboard0, make, "2", TO, "toggleRPGhud();");
NewActionMap("pdaMap.sae");
bindCommand(keyboard0, make, "enter", TO, "$CmdHUD::State = CmdHUD::Cursor(!$CmdHUD::State);");
