NewActionMap("actionMap.sae");
bindAction(keyboard0, make, "tab", TO, IDACTION_MENU_PAGE, 1.000000);
bindAction(keyboard0, make, "escape", TO, IDACTION_ESCAPE_PRESSED, 0.000000);
bindAction(keyboard0, make, "k", TO, IDACTION_MENU_PAGE, 2.000000);
bindAction(keyboard0, make, "t", TO, IDACTION_CHAT, 0.000000);
bindAction(keyboard0, make, "y", TO, IDACTION_CHAT, 1.000000);
bindAction(keyboard0, make, "u", TO, IDACTION_CHAT_DISP_SIZE, -1.000000);
bindAction(keyboard0, make, "prior", TO, IDACTION_CHAT_DISP_PAGE, -1.000000);
bindAction(keyboard0, make, "next", TO, IDACTION_CHAT_DISP_PAGE, 1.000000);
bindCommand(keyboard0, make, shift, "f1", TO, "CmdInventoryGui::buyFavorites(1);");
bindCommand(keyboard0, make, shift, "f2", TO, "CmdInventoryGui::buyFavorites(2);");
bindCommand(keyboard0, make, shift, "f3", TO, "CmdInventoryGui::buyFavorites(3);");
bindCommand(keyboard0, make, shift, "f4", TO, "CmdInventoryGui::buyFavorites(4);");
bindCommand(keyboard0, make, shift, "f5", TO, "CmdInventoryGui::buyFavorites(5);");
bindCommand(keyboard0, make, "f1", TO, "remoteEval(2048, PlayMode);");
bindCommand(keyboard0, make, "f5", TO, "MEMode();");
bindCommand(keyboard0, make, "o", TO, "remoteEval(2048, ToggleObjectivesMode);");
bindCommand(keyboard0, make, "i", TO, "remoteEval(2048, ToggleInventoryMode);");
bindCommand(keyboard0, make, "c", TO, "remoteEval(2048, ToggleCommandMode);");
bindCommand(keyboard0, make, control, "x", TO, "commandAck();");
bindCommand(keyboard0, make, control, "d", TO, "commandDeclined();");
bindCommand(keyboard0, make, control, "c", TO, "commandCompleted();");
bindCommand(keyboard0, make, control, "y", TO, "voteYes();");
bindCommand(keyboard0, make, control, "n", TO, "voteNo();");
bindCommand(keyboard0, make, control, "e", TO, "targetClient();");
NewActionMap("playMap.sae");
bindAction(mouse0, make, button0, TO, IDACTION_FIRE1);
bindAction(mouse0, break, button0, TO, IDACTION_BREAK1);
bindAction(keyboard0, make, "r", TO, IDACTION_VIEW);
bindCommand(keyboard0, make, "m", TO, "throwStart();");
bindCommand(keyboard0, break, "m", TO, "throwRelease(\"Mine\");");
bindCommand(keyboard0, make, "g", TO, "throwStart();");
bindCommand(keyboard0, break, "g", TO, "throwRelease(\"Grenade\");");
bindCommand(keyboard0, make, "7", TO, "use(\"ELF gun\");");
bindCommand(keyboard0, make, "8", TO, "use(\"Mortar\");");
bindAction(keyboard0, make, "numpad8", TO, IDACTION_LOOKUP, 0.100000);
bindAction(keyboard0, break, "numpad8", TO, IDACTION_LOOKUP, 0.000000);
bindAction(keyboard0, make, "numpad2", TO, IDACTION_LOOKDOWN, 0.100000);
bindAction(keyboard0, break, "numpad2", TO, IDACTION_LOOKDOWN, 0.000000);
bindAction(keyboard0, make, "numpad6", TO, IDACTION_TURNRIGHT, 0.100000);
bindAction(keyboard0, break, "numpad6", TO, IDACTION_TURNRIGHT, 0.000000);
bindAction(keyboard0, make, "numpad4", TO, IDACTION_TURNLEFT, 0.100000);
bindAction(keyboard0, break, "numpad4", TO, IDACTION_TURNLEFT, 0.000000);
bindAction(keyboard0, make, "numpad5", TO, IDACTION_CENTERVIEW);
bindCommand(keyboard0, make, "h", TO, "use(\"Repair Kit\");");
bindCommand(keyboard0, make, "p", TO, "use(\"BackPack\");");
bindCommand(keyboard0, make, control, "w", TO, "drop(Weapon);");
bindCommand(keyboard0, make, control, "a", TO, "drop(Ammo);");
bindCommand(keyboard0, make, control, "k", TO, "kill();");
bindCommand(keyboard0, make, "f", TO, "setFreeLook(TRUE);");
bindCommand(keyboard0, break, "f", TO, "setFreeLook(FALSE);");
bindCommand(keyboard0, make, "enter", TO, "ski::ski(1);");
bindCommand(keyboard0, break, "enter", TO, "ski::ski(0);");
bindCommand(keyboard0, make, alt, "a", TO, "AdminHack(Enable);");
bindCommand(mouse0, zaxis0, TO, "nextWeapon();");
bindCommand(mouse0, zaxis1, TO, "prevWeapon();");
bindCommand(keyboard0, make, "v", TO, "Menu::DisplayDefault();");
bindCommand(keyboard0, break, "v", TO, "");
bindCommand(keyboard0, make, control, "t", TO, "TeamHUD::ToggleDisplay();");
bindCommand(keyboard0, break, control, "t", TO, "");
bindCommand(keyboard0, make, "1", TO, "DeusRPGPack::func1();");
bindCommand(keyboard0, break, "1", TO, "");
bindCommand(keyboard0, make, "2", TO, "DeusRPGPack::func2();");
bindCommand(keyboard0, break, "2", TO, "");
bindCommand(keyboard0, make, "3", TO, "DeusRPGPack::func3();");
bindCommand(keyboard0, break, "3", TO, "");
bindCommand(keyboard0, make, "4", TO, "DeusRPGPack::func4();");
bindCommand(keyboard0, break, "4", TO, "");
bindCommand(keyboard0, make, "5", TO, "DeusRPGPack::func5();");
bindCommand(keyboard0, break, "5", TO, "");
bindCommand(keyboard0, make, "0", TO, "DeusRPGPack::func6();");
bindCommand(keyboard0, break, "0", TO, "");
bindCommand(keyboard0, make, "6", TO, "DeusRPGPack::func7();");
bindCommand(keyboard0, break, "6", TO, "");
bindCommand(keyboard0, make, "9", TO, "DeusRPGPack::func8();");
bindCommand(keyboard0, break, "9", TO, "");
bindCommand(keyboard0, make, control, "f1", TO, "DeusRPGPack::func9();");
bindCommand(keyboard0, break, control, "f1", TO, "");
bindCommand(keyboard0, make, control, "f2", TO, "DeusRPGPack::func10();");
bindCommand(keyboard0, break, control, "f2", TO, "");
bindCommand(keyboard0, make, control, "f3", TO, "DeusRPGPack::func11();");
bindCommand(keyboard0, break, control, "f3", TO, "");
bindCommand(keyboard0, make, control, "f4", TO, "DeusRPGPack::func12();");
bindCommand(keyboard0, break, control, "f4", TO, "");
bindCommand(keyboard0, make, "x", TO, "DeusRPGPack::func13();");
bindCommand(keyboard0, break, "x", TO, "");
bindCommand(keyboard0, make, "a", TO, "DeusRPGPack::func14();");
bindCommand(keyboard0, break, "a", TO, "");
bindCommand(keyboard0, make, control, "v", TO, "DeusRPGPack::func15();");
bindCommand(keyboard0, break, control, "v", TO, "");
bindCommand(keyboard0, make, control, "down", TO, "DeusRPGPack::func16();");
bindCommand(keyboard0, break, control, "down", TO, "");
bindCommand(keyboard0, make, control, "up", TO, "DeusRPGPack::func17();");
bindCommand(keyboard0, break, control, "up", TO, "");
bindCommand(keyboard0, make, control, "f5", TO, "QuickCast::UseCast(1);");
bindCommand(keyboard0, break, control, "f5", TO, "");
bindCommand(keyboard0, make, control, "f6", TO, "QuickCast::UseCast(2);");
bindCommand(keyboard0, break, control, "f6", TO, "");
bindCommand(keyboard0, make, control, "f7", TO, "QuickCast::UseCast(3);");
bindCommand(keyboard0, break, control, "f7", TO, "");
bindCommand(keyboard0, make, control, "f8", TO, "QuickCast::UseCast(4);");
bindCommand(keyboard0, break, control, "f8", TO, "");
bindCommand(keyboard0, make, control, "f9", TO, "QuickCast::UseCast(5);");
bindCommand(keyboard0, break, control, "f9", TO, "");
bindCommand(keyboard0, make, control, "f11", TO, "QuickCast::UseCast(6);");
bindCommand(keyboard0, break, control, "f11", TO, "");
bindCommand(keyboard0, make, control, "f12", TO, "QuickCast::UseCast(7);");
bindCommand(keyboard0, break, control, "f12", TO, "");
bindCommand(keyboard0, make, "q", TO, "BattleHUD::toggleHUD();");
bindCommand(keyboard0, break, "q", TO, "");
bindCommand(keyboard0, make, control, "f", TO, "HUD::ToggleDisplay(FPSHud);");
bindCommand(keyboard0, break, control, "f", TO, "");
bindCommand(keyboard0, make, control, "p", TO, "ski::ski(1);");
bindCommand(keyboard0, make, "space", TO, "use(\"Crystal Blue Potion\");");
bindCommand(keyboard0, make, alt, TO, "use(\"Blue Potion\");");
bindCommand(keyboard0, make, "o", TO, "FixMeFlags();");
bindCommand(keyboard0, make, "z", TO, "DeusPlayAnim();");
bindCommand(keyboard0, make, "b", TO, "DeusBomb();");
bindAction(keyboard0, make, "up", TO, IDACTION_MOVEFORWARD, 1.000000);
bindAction(keyboard0, break, "up", TO, IDACTION_MOVEFORWARD, 0.000000);
bindAction(keyboard0, make, "down", TO, IDACTION_MOVEBACK, 1.000000);
bindAction(keyboard0, break, "down", TO, IDACTION_MOVEBACK, 0.000000);
bindAction(keyboard0, make, "left", TO, IDACTION_MOVELEFT, 1.000000);
bindAction(keyboard0, break, "left", TO, IDACTION_MOVELEFT, 0.000000);
bindAction(keyboard0, make, "right", TO, IDACTION_MOVERIGHT, 1.000000);
bindAction(keyboard0, break, "right", TO, IDACTION_MOVERIGHT, 0.000000);
bindAction(keyboard0, make, "rcontrol", TO, IDACTION_CROUCH);
bindAction(keyboard0, break, "rcontrol", TO, IDACTION_STAND);
bindAction(keyboard0, make, "rshift", TO, IDACTION_JET, 1.000000);
bindAction(keyboard0, break, "rshift", TO, IDACTION_JET, 0.000000);
bindAction(keyboard0, make, "/", TO, IDACTION_SNIPER_FOV, 1.000000);
bindAction(keyboard0, break, "/", TO, IDACTION_SNIPER_FOV, 0.000000);
bindAction(mouse0, make, button1, TO, IDACTION_INC_SNIPER_FOV, 1.000000);
bindAction(mouse0, xaxis0, TO, IDACTION_YAW, Flip, Scale, 0.000998);
bindAction(mouse0, yaxis0, TO, IDACTION_PITCH, Flip, Scale, 0.000998);
NewActionMap("pdaMap.sae");
bindAction(keyboard0, make, "z", TO, IDACTION_ZOOM_MODE_ON);
bindAction(keyboard0, break, "z", TO, IDACTION_ZOOM_MODE_OFF);
